### ISSUE TITLE
Implementation of `/api/v1/text/task/generation-detection`

### ISSUE THREAD

**Issue by evaline-ju** [foundation-model-stack/fms-guardrails-orchestrator#122]
## Description

As an orchestrator user, I want to be able to use orchestrator to call detectors that require both user prompts and generated text from LLMs, so that I can use detectors in my pipeline that may require both as input.

This `/api/v1/text/task/generation-detection` endpoint is expected to work with the [Detector API](https://foundation-model-stack.github.io/fms-guardrails-orchestrator/?urls.primaryName=Detector+API) `/text/generation` endpoint which primarily needs user `prompt` and generated text from the LLM (`model_id`) provided in [Orchestrator API](https://foundation-model-stack.github.io/fms-guardrails-orchestrator/?urls.primaryName=Orchestrator+API)

## Discussion

Since the generated text needs to be present for the detector, we will only assume unary calls to the LLM for now (no streaming - otherwise aggregation and awaiting the generation stream would have to happen anyway)

## Acceptance Criteria

- [ ] Unit tests cover new/changed code
- [ ] Examples build against new/changed code
- [ ] READMEs are updated
- [ ] Type of [semantic version](https://semver.org/) change is identified

**Comment by mdevino** [comment]
Hello, should results be sorted by the order detectors are listed?

Consider the example below.

Sample request:

```json
{
	"model_id": "my_awesome_llm",
	"prompt": "What is the capital of Brazil?",
	"detectors": {
		"answer_relevance": {},
		"answer_correctness": {}
	}
}
```

Response:

```json
{
	"generated_text": "The capital of Brazil is Rio de Janeiro.",
	"detections": [
		{
			"detection_type": "correctness",
			"detection": "answer_correctness",
			"score": 0.00027292477898299694
		},
		{
			"detection_type": "relevance",
			"detection": "answer_relevance",
			"score": 0.9994032433605752
		}
	],
	"input_token_count": 7
}
```

The order in which detectors are listed in the request is `answer_relevance`, then `answer_correctness`, but the response returns detections in the reverse order.

Is this acceptable?


Some context (but unnecessary for the question):  `answer_relevance` checks if the model answers what was asked. while `answer_correctness` checks if the answer is factually correct.
