### ISSUE TITLE
Migrate clients implementation from `reqwest` to `hyper`

### ISSUE THREAD

**Issue by pscoro** [foundation-model-stack/fms-guardrails-orchestrator#247]
## Description
As part of efforts to introduce middleware sensibly into the orchestrator we would like to first migrate away from `reqwest` and instead use `hyper` for the underlying HTTP clients. We want to do this in order to avoid limitations and conflicts imposed by `reqwest` that switching to a lower level library would avoid. In particular, we care about using `tower::Service` for middleware in the near future.

## Acceptance Criteria
- all http clients use Request, RequestBuilder, Client, etc from `hyper` instead of `reqwest` (the openai client may be exempt as HTTP streaming will have its own complexities
- all handler functions are updated to build and send `hyper` requests
- `hyper` clients are properly configurable and tls certs are being handled without `reqwest` (likely using `hyper-rustls`)

**Comment by gkumbhat** [comment]
Closing as PR is merged now
