### ISSUE TITLE
Migrate openai client and HTTP streaming support from `reqwest` to `hyper`

### ISSUE THREAD

**Issue by pscoro** [foundation-model-stack/fms-guardrails-orchestrator#248]
## Description
As a follow up to https://github.com/foundation-model-stack/fms-guardrails-orchestrator/issues/247 we need to also support HTTP streaming without using any `reqwest` related crates. The previously implementation using `reqwest_eventsource` will need to be replaced. The openai client is the only client to currently use HTTP streaming (rest are gRPC), so it may make sense to port the openai client from `reqwest` to `hyper` on its own as part of this issue.

## Acceptance Criteria
- sensible solution to HTTP streaming support using `hyper`
- openai client uses `hyper` and whatever replacement streaming implementation in order to source SSE events

**Comment by gkumbhat** [comment]
closing as the PR is merged
