### ISSUE TITLE
Implement whole document "chunker"

### ISSUE THREAD

**Issue by evaline-ju** [foundation-model-stack/fms-guardrails-orchestrator#53]
## Description

As a user that may want to use various detectors, I may want to use detectors that do not require "chunking." Particularly, some detectors like regexes may just operate on entire documents.

## Discussion

For consistency with detectors that will invoke chunkers, we will implement a "default" whole document chunker that just returns a span with the start and end corresponding to an entire input document. Any detectors that do not specify a chunker will use this default one. 

For code organization purposes, we likely want to implement this not as branching logic in the orchestrator itself but as a separate chunker that can get called via some name (still implemented within the orchestrator repo, but from a deployment/user configuration POV, this name can be still be specified in the config).

## Acceptance Criteria

- [ ] Unit tests cover new/changed code
- [ ] Examples build against new/changed code
- [ ] READMEs are updated
- [ ] Type of [semantic version](https://semver.org/) change is identified

**Comment by declark1** [comment]
> For code organization purposes, we likely want to implement this not as branching logic in the orchestrator itself but as a separate chunker that can get called via some name (still implemented within the orchestrator repo, but from a deployment/user configuration POV, this name can be still be specified in the config).

Hmm, I don't think this approach will fit with the current design. We delegate to the `ChunkerClient`, which wraps the underlying `ChunkersServiceClient`s. As this "default" implementation would not be an actual grpc `ChunkersServiceClient` (which is a struct, not a trait that we can implement a `DefaultChunkerServiceClient` for), this wouldn't work.

I can propose some alternative ways to implement this, if interested.

**Comment by gkumbhat** [comment]
@declark1 definitely let us know some alternatives. The idea here was to not have yet another branching logic, like `if chunker not configured` or `if chunker is default` and instead have a stock implementation of a chunker that instead of making an external calls, returns the response based on the input text directly but in the format that the "chunker" itself would do.
