### ISSUE TITLE
Update HTTP client creation for mTLS

### ISSUE THREAD

**Issue by evaline-ju** [foundation-model-stack/fms-guardrails-orchestrator#69]
## Description

As an orchestrator developer, I want to update the HTTP client creation, so that I can use mTLS for use with detectors, which are expected to be REST servers [as opposed to GRPC servers].

## Discussion

It appears that while the created GRPC client uses `client_ca_cert_path` etc, the HTTP client We are generally expecting the same "format" of cert information regardless of GRPC or HTTP servers.

Ref: https://github.com/foundation-model-stack/fms-guardrails-orchestrator/blob/main/src/clients.rs

## Acceptance Criteria

- [x] Unit tests cover new/changed code
- [ ] Examples build against new/changed code
- [ ] READMEs are updated
- [ ] Type of [semantic version](https://semver.org/) change is identified

**Comment by declark1** [comment]
Example for reference:
https://github.com/ttys3/rust-mtls-axum-example/blob/45d07d3545a1affeeaf854dc6c4d1d7b3417c5fd/src/main.rs#L111
