### ISSUE TITLE
API response field different from v1.0: generated_text (v1.0) --> text_generated (v2.0)

### ISSUE THREAD

**Issue by flaviabeo** [foundation-model-stack/fms-guardrails-orchestrator#72]
## Describe the bug

The new v2.0 API json response is returning different field name than the v1.0.

## Sample Code

Please include a minimal sample of the code that will (if possible) reproduce the bug in isolation

## Expected behavior

```json
{
  "generated_text": "I love dogs love@dogs.com",
  "token_classification_results": {
    "input": null,
    "output": []
  },
  "finish_reason": "MAX_TOKENS",
  "generated_token_count": 99,
  "seed": 42,
  "input_token_count": 21,
  "warnings": null,
  "tokens": [
    {
      "text": "\u0120not",
      "logprob": 0.0,
      "rank": 1
    }],
  "input_tokens": []
  }
```

## Observed behavior

```json
{
  "text_generated": "I hate cats. [...] I love dogs love@dogs.com!",
  "token_classification_results": {},
  "finish_reason": "EOS_TOKEN",
  "generated_token_count": 59,
  "seed": 0,
  "input_token_count": 21
}
```

**Comment by declark1** [comment]
Hmm, this is strange. The field is definitely still called `generated_text` in 2.0.

**Comment by flaviabeo** [comment]
Ok! I think updating the deployment, this is fixed! This is the image being pulled: `us.icr.io/cil15-shared-registry/fms-orchestr8:latest`
