### ISSUE TITLE
 v2.0 finish_reason responds with EOS_TOKEN instead of MAX_TOKENS.

### ISSUE THREAD

**Issue by flaviabeo** [foundation-model-stack/fms-guardrails-orchestrator#74]
## Describe the bug

When running functional tests, calling the `/api/v1/task/classification-with-text-generation` end point through:

```python
response = requests.post(url="https://gr2-fmaas-tuning.apps.fmaas-devstage-backend.fmaas.res.ibm.com/api/v1/task/classification-with-text-generation", json=PAYLOAD, headers=HEADERS, verify=SSL)
json_response = json.loads(response.content.decode(response.encoding))
```

## Platform

Please provide details about the environment you are using, including the following:

- fms-orchestrator image version: `us.icr.io/cil15-shared-registry/fms-orchestr8:latest`

## Expected behavior

The previous response at v1.0 was:
```json
{
  "generated_text": "I love dogs love@dogs.com",
  "token_classification_results": {
    "input": null,
    "output": []
  },
  "finish_reason": "MAX_TOKENS",
  "generated_token_count": 99,
  "seed": 42,
  "input_token_count": 21,
  "warnings": null,
  "tokens": [
    {
      "text": "\u0120not",
      "logprob": 0.0,
      "rank": 1
    }],
  "input_tokens": []
  }
```
`finish_reason` value is expected to be "MAX_TOKENS".

## Observed behavior

The actual response is:
```json
{
  "generated_text": "I hate cats they are stupid. I love dogs love@dogs.com",
  "token_classification_results": {},
  "finish_reason": "EOS_TOKEN",
  "generated_token_count": 59,
  "seed": 0,
  "input_token_count": 21
}
```
`finish_reason` value is "EOS_TOKEN".

## Additional context

The functional test run to get this error is:

```python
    def test_unary_no_guardrails():
        response = requests.post(url=UNARY_GUARDRAILS_URL, json=PAYLOAD, headers=HEADERS, verify=SSL)
        assert 200 == response.status_code
        json_response = json.loads(response.content.decode(response.encoding))
>       assert json_response["finish_reason"] == "MAX_TOKENS"
E       AssertionError: assert 'EOS_TOKEN' == 'MAX_TOKENS'
E         - MAX_TOKENS
E         + EOS_TOKEN
```

**Comment by declark1** [comment]
Can you share the parameters and text used for this request? From the result above, it appears that the seed was not set in the 2.0 request. I also notice that the 1.0 response returns 99 tokens, which is higher than the TGIS default. Was this parameter explicitly set? If not, I wonder if caikit applies a different `max_tokens` default.

**Comment by gkumbhat** [comment]
Thanks @mdevino for picking this up. Please add a unit test for this after fixing. Example: https://github.com/foundation-model-stack/fms-guardrails-orchestrator/blob/main/src/orchestrator.rs#L734

**Comment by alanbraz** [comment]
Problem is that GR API decoding_method value is `SAMPLING` while TGIS is expecting `SAMPLE`
Convert in this line and will make the correct call to TGIS and return the correct stop reason. That is wrong because the default is `GREEDY`.
https://github.com/foundation-model-stack/fms-guardrails-orchestrator/blob/4973351d25f7954aed8475f0b40b00678d071eb6/src/models.rs#L586

**Comment by mdevino** [comment]
After some discussion, let's close this issue and make sure we call the API using "SAMPLE" instead of "SAMPLING", so we align with what TGIS expects.
