### ISSUE TITLE
Failed to deserialize the JSON body into the target type: missing field `models`

### ISSUE THREAD

**Issue by pmcjr** [foundation-model-stack/fms-guardrails-orchestrator#91]
## Describe the bug

When calling `/api/v1/task/classification-with-text-generation` with a missing `models` object inside `guardrail_config.input` or `guardrail_config.output` objects in the payload, a `422 Failed to deserialize the JSON body` response occurs.

## Platform

Please provide details about the environment you are using, including the following:

```
fms-orchestrator image version: fms-guardrails-orchestr8:e5b72c1
```

## Observed behavior

Request body
```
{
	"inputs": "My email is",
	"model_id": "<model-id>",
	"guardrail_config": {
		"input": {
			"models": {}
		},
		"output": {
		}
	}
}
```

Response
```
Failed to deserialize the JSON body into the target type: guardrail_config.output: missing field `models` at line 9 column 3
```

## Additional context 

It happens for both `guardrail_config.output` and `guardrail_config.input`.

**Comment by declark1** [comment]
Completed with https://github.com/foundation-model-stack/fms-guardrails-orchestrator/pull/99
